version: "3.8"

services:
  #API configuration
  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    env_file:
      - ./services/api/.env
    networks:
      - api
    volumes:
      - ./packages:/home/ubuntu/packages
      - ./services/api/build:/home/ubuntu/services/api/build
      - ./services/api/node_modules:/home/ubuntu/services/api/node_modules
    command: yarn workspace @naval-combat-server/api start:local
    depends_on:
      - mongo
    ports:
      - "4000:4000"

  #Notification configuration
  socket:
    build:
      context: .
      dockerfile: ./services/notification/Dockerfile
    env_file:
      - ./services/notification/.env
    networks:
      - socket
    volumes:
      - ./packages:/home/ubuntu/packages
      - ./services/notification/build:/home/ubuntu/services/notification/build
      - ./services/notification/node_modules:/home/ubuntu/services/notification/node_modules
    command: yarn workspace @naval-combat-server/notification start:local
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  #Redis configuration
  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - socket

  #MongoDB configuration
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "8080:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - mongo
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mongo-workbench:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      - mongo

networks:
  api:
    driver: bridge
  socket:
    driver: bridge
  mongo:
    driver: bridge