version: "3.8"

services:
  #API configuration
  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    env_file:
      - ./services/api/.env
    networks:
      - api
    volumes:
      - ./services/api/build:/home/ubuntu/services/api/build
      - ./services/api/node_modules:/home/ubuntu/services/api/node_modules
    command: yarn workspace @event-boilerplate/api start:local
    ports:
      - "4000:4000"

  #Notification configuration
  socket:
    build:
      context: .
      dockerfile: ./services/notification/Dockerfile
    env_file:
      - ./services/notification/.env
    networks:
      - socket
    volumes:
      - ./services/notification/build:/home/ubuntu/services/notification/build
      - ./services/notification/node_modules:/home/ubuntu/services/notification/node_modules
    command: yarn workspace @event-boilerplate/notification start:local
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  #Redis configuration
  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - socket

networks:
  api:
    driver: bridge
  socket:
    driver: bridge