name: Pull Request

on: pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: node:14
 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Compile test dependencies
        run: yarn test:compile

      - name: Run tests
        run: yarn test