name: Deploy

on:
  release:
    types: [prereleased]

env:
  REGION: sa-east-1
  SERVICE: naval-combat
  ECR_ALIAS: main
  ENV: stg

jobs:
  deploy-notification:
    env:
      APPLICATION: notification

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Compile project
        run: |
          yarn ci:compile
          yarn workspace @naval-combat-server/${{ env.APPLICATION }} ci:compile

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_ALIAS }}-${{ env.ENV }}
          IMAGE_NAME: ${{ env.SERVICE }}-${{ env.APPLICATION }}-${{ env.ENV }}
        run: |
          docker build -f ./services/${{ env.APPLICATION }}/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_NAME }}_latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_NAME }}_latest
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_NAME }}_latest"

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.SERVICE }}-${{ env.APPLICATION }}-${{ env.ENV }} --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: render-main-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.APPLICATION }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-main-container.outputs.task-definition }}
          service: ${{ env.SERVICE }}-${{ env.APPLICATION }}-${{ env.ENV }}
          cluster: ${{ env.SERVICE }}-${{ env.ENV }}
          wait-for-service-stability: true

  deploy-lambda:
    env:
      APPLICATION: api

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.REGION}}

      - name: Compile Dependencies
        run: |
          yarn ci:compile
      
      - name: Compile project
        run: |
          yarn workspace @naval-combat-server/${{ env.APPLICATION }} ci:compile
      
      - name: Zip release
        run: |
          cd services/api
          zip -r -qq release.zip build
          mv release.zip ../../release.zip

      - name: Update lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.SERVICE }}-api-${{ env.ENV }} \
            --zip-file fileb://release.zip \
            --publish